
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Job;
import model.SaveResult;
import service.JobDAOImpl;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author tmg
 */
public class ModificarJob extends javax.swing.JFrame {

    /**
     * Creates new form ModificarJob
     */
    public ModificarJob() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    public ModificarJob(
            TablaJob tablaJob,
            int filaSeleccionada,
            String jobId,
            String jobTitle,
            String minSalary,
            String maxSalary,
            MenuInicio menuInicio
     ){
        initComponents();
        inputModificarJobId.setText(jobId);
        inputModificarJobTitulo.setText(jobTitle);
        inputModificarSalarioMinimo.setText(minSalary);
        inputModificarSalarioMaximo.setText(maxSalary);
        this.menuInicio = menuInicio;
        this.tablaJob = tablaJob;
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        inputModificarJobId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        inputModificarJobTitulo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        inputModificarSalarioMinimo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        inputModificarSalarioMaximo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MODIFICAR JOB", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        jLabel1.setText("JOB ID");

        inputModificarJobId.setEditable(false);

        jLabel2.setText("Job Titulo");

        jLabel3.setText("Salario Minimo");

        inputModificarSalarioMinimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputModificarSalarioMinimoActionPerformed(evt);
            }
        });

        jLabel4.setText("Salario Maximo");

        jButton1.setText("ACEPTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("CANCELAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputModificarJobId)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputModificarJobTitulo)
                    .addComponent(inputModificarSalarioMinimo)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputModificarSalarioMaximo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputModificarJobId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputModificarJobTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputModificarSalarioMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputModificarSalarioMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton2});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputModificarSalarioMinimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputModificarSalarioMinimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputModificarSalarioMinimoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String jobId = inputModificarJobId.getText();
       String jobTitle = inputModificarJobTitulo.getText();
       String minSalary = inputModificarSalarioMinimo.getText();
       String maxSalary = inputModificarSalarioMaximo.getText();
       
       if( jobId.isEmpty() 
                    || jobTitle.isEmpty() 
                    || minSalary.isEmpty() 
                    || maxSalary.isEmpty() 
                ){
                JOptionPane.showMessageDialog(this,
                        "Verifique los campos ingresados",
                        "Intente nuevamente",
                        JOptionPane.ERROR_MESSAGE);
            } else {  
                Job job = new Job();
                job.setJobId(jobId);
                job.setJobTitle(jobTitle);
                job.setMinSalary(Double.valueOf(minSalary));
                job.setMaxSalary(Double.valueOf(maxSalary));


                 try {
                    actualizarJobs(job);

                } catch (SQLException ex) {
                    Logger.getLogger(TablaEmployee.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this,
                    "Error al conectar a la base de datos:\n" + ex.getMessage(),
                     "Error",
                     JOptionPane.ERROR_MESSAGE);
                }
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void actualizarJobs(Job job) throws SQLException {
        JobDAOImpl jobDAOImpl = new JobDAOImpl(menuInicio.usuario, menuInicio.ip, menuInicio.puerto);
        SaveResult resultado = jobDAOImpl.update(job);
        
        try {
            if (resultado.getSuccess()) {
                tablaJob.actualizarTabla();
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, resultado.getMessage(), "Error de alta", JOptionPane.ERROR_MESSAGE);
            } 
        }catch(Exception e){
             JOptionPane.showMessageDialog(this,
                "Error al conectar a la base de datos:\n" + e.getMessage(),
                 "Error",
                 JOptionPane.ERROR_MESSAGE);
        } 
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField inputModificarJobId;
    private javax.swing.JTextField inputModificarJobTitulo;
    private javax.swing.JTextField inputModificarSalarioMaximo;
    private javax.swing.JTextField inputModificarSalarioMinimo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    private int filaSeleccionada;
    private MenuInicio menuInicio;
    private TablaJob tablaJob;

}
